# static cofiguration

# providers for dynamic cofiguration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
  file:
    directory: "/dyn-config/"
    watch: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    transport:
      respondingTimeouts:
        readTimeout: 10s
        writeTimeout: 10s
        idleTimeout: 60s
      lifeCycle:
        requestAcceptGraceTimeout: 10s
        graceTimeOut: 20s

api:
  dashboard: true

metrics:
  prometheus: {}

ping: {}
accessLog: {}
log:
  level: DEBUG
